# Generated by Django 4.1 on 2022-09-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('cPassword', models.CharField(max_length=20)),
                ('old_password', models.CharField(blank=True, default='', max_length=20)),
                ('new_password', models.CharField(blank=True, default='', max_length=20)),
                ('reenter_password', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
    ]
